enum StreetNosheryOnboardingEnums{
  MOBILE_VERIFICATION,
  EMAIL_VERIFICATION,
  ADDRESS_VERIFICATION
}

enum UserStatus {
  MOBILE_VERIFICATION,
  EMAIL_VERIFICATION,
  USER_DETAILS_VERIFICATION,
  FAILED,
  UNKNOWN // Fallback for unexpected values
}